### ISSUE TITLE
Plug-in unexpected indent spams skipped message

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-base#201] opened 2015-07-02 05:03 UTC
When a Plug-in has unexpected indentation (which is a problem in itself) it's logging the same message many times. It doesn't show up logged in `pyblish-qml`, but in Maya's script editor (the log) it shows:

```
pyblish_magenta: Registered E:\Projects\pyblish-magenta\pyblish_magenta\plugins
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.collect_conceptart.CollectConceptArt : Selecting concept art.. # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.collect_maya_current_file.CollectMayaCurrentFile : Collecting Maya Work File.. # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
# pyblish.collect_asset.CollectAsset : Collecting Asset.. # 
# pyblish.plugin : Skipped: "validate_units" (unexpected indent (validate_units.py, line 8)) # 
```

Is this expected behavior?

An example plug-in with unexpected indentation:

``` python
import pyblish.api


@pyblish.api.log
class ValidateUnits(pyblish.api.Validator):
   """Validate the scene linear, angular and time units."""

    def process(self, context):
        units = context.data('units')
        if units and units != 'cm':
            raise RuntimeError("Scene linear units must be centimeters")

        units_angle = context.data('units_angle')
        if units_angle and units_angle != 'deg':
            raise RuntimeError("Scene angular units must be degrees")

        fps = context.data('fps')
        if fps and fps != 25.0:
            raise RuntimeError("Scene must be 25 FPS")
```

Note that the docstring should need one space more.

**Comment by mottosso** [comment] 2015-07-02 05:40
Interesting, it only seems to happen when publishing via the GUI. Not the expected behaviour.

**Comment by mottosso** [comment] 2015-07-09 06:40
Something similar happened to @tokejepsen 

![image](https://cloud.githubusercontent.com/assets/2152766/8589401/b1963f40-260d-11e5-8daa-80d96964aab9.png)

It suggests that `discover()` is being called multiple times, meaning plug-ins are being loaded off of disk each time. It's possibly a bottleneck, especially under conditions where plug-ins are hosted on a network and the network is slow.

**Comment by tokejepsen** [comment] 2015-07-09 07:49
> Something similar happened to @tokejepsen

I as thinking that it might be something with the slow-down in Nuke?

**Comment by mottosso** [comment] 2015-07-09 07:51
Probably not, you would have been experiencing the same issues in Maya too. But it probably slows things down overall.

**Comment by tokejepsen** [comment] 2015-07-09 08:21
Can just confirm that we are getting similar results in Maya;

```

# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
# pyblish.collect_context_version.SelectContextVersion : Publish Version: 5 # 
# pyblish.plugin : Paths from environment: ['K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-deadline-dev\\pyblish_deadline\\plugins', 'K:\\tools\\Pyblish\\pyblish-ftrack-dev\\pyblish_ftrack\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins', 'K:\\tools\\Pyblish\\pyblish-bumpybox-dev\\pyblish_bumpybox\\plugins\\maya'] # 
# pyblish.plugin : Skipped: "select_deadline_mantra_nodes" (No module named hou) # 
# pyblish.plugin : Skipped: "select_deadline_write_nodes" (No module named nuke) # 
```

**Comment by mottosso** [comment] 2015-07-09 08:26
Looking into this now.

**Comment by mottosso** [comment] 2015-07-09 08:36
Ok, got it.

The problem was that [Pyblish RPC](https://github.com/pyblish/pyblish-rpc/issues/4) was calling `pyblish.api.discover()` **per process**. Which means that the more processing you did, and the more plug-ins you had registered, it would get exponentially slower.

You should be seeing a noticeable speed increase with this fixed.

**Comment by mottosso** [comment] 2015-07-09 08:53
Fixed in https://github.com/pyblish/pyblish-rpc/issues/4

**Closed as completed by mottosso** 2015-07-09 08:53 UTC
Labels: bug

**Comment by mottosso** [comment] 2015-07-10 08:58
@tokejepsen Did you notice any difference in performance since this fix?

**Comment by tokejepsen** [comment] 2015-07-10 09:06
> @tokejepsen Did you notice any difference in performance since this fix?

Haven't worked with it enough to tell. Will do a test at some point.

**Comment by BigRoy** [comment] 2015-07-19 15:42
I've been testing Pyblish mostly loading everything from an SSD and it was already running pretty fast. But with this fixed I noticed it became even faster.

I hope to do some more testing from a network server soon to see if it helped much in that area.

**Comment by mottosso** [comment] 2015-07-19 15:57
Networks are what cause the most slow-down unfortunately.

Networks and file-systems in CG are typically optimised for faster transfers of large files, leaving access to many small files behind. With good reason, of course, a majority of files are large (e.g. 1 mb +).

Some studios do a combination of both, storing large files on a file-system and served via a network better suited for large files, whereas smaller files are served from a different file-system, different network, but then joined together either locally or via a proxy of sorts, making them act as though they were one and the same file-system, but with optimal performance on all fronts. That's the environment where Pyblish would thrive the most, currently.

I've had a few thoughts about how to better handle this. It could be as simple as to deploy all plug-ins as a single zip-archive on your end, loading them all into memory on first run. It would gain all of the benefits of an optimised network, with only a little overhead on deployment; i.e. you would need to zip them for each update you do. But a lot of that could be automated, especially if you already use a version control system for deployment as most (sane) studios do.
