### ISSUE TITLE
Unable to save orderedDict to context

### ISSUE THREAD

**Issue by mkolar** [pyblish/pyblish-base#237] opened 2015-12-10 16:04 UTC
I have a situation where it would be very helpful to be able to save orderedDict into a data member on context, however when I try, it give me following error

`<Fault 1:"<type 'exceptions.TypeError'>:cannot marshal <class 'collections.OrderedDict'> objects">`
`Stopped resetting due to unknown result, check your test?`

what I'm doing is simple `context.data['ftrackData'] = ftrack_data` where `ftrack_data` is OrderedDict.

I can of course work around it by just using plain dictionary, however ordered would make lot of things much easier. In this particular case I'd like to rely on it when recreating hierarchy of given task from ftrack data.

**Comment by mottosso** [comment] 2015-12-10 16:14
It makes sense that this doesn't work the way things are currently implemented, but they should, so I'm marking this as a bug and pull-requests are welcome.

As far as I can tell, the problem is coming from here, during the call to "validate".
- [https://github.com/pyblish/pyblish-rpc/blob/master/pyblish_rpc/formatting.py#L45](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/formatting.py#L45)

In a nutshell, the GUI is getting a copy of all data but is only capable of receiving data the can be serialised into JSON. A simple test for this, is to pass whatever data you have in mind for `json.dumps`.

A solution could be to simply _not_ send something that isn't supported, as is happening with data in general, see [here](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/formatting.py#L138).

Another solution is to not forward _any_ data, not even during results, as they currently aren't used in the GUI anyway. The idea was to implement a "data browser", which is why this data is going across currently, but it simply hasn't been implemented yet and as such this transfer is not necessary.

**Comment by BigRoy** [comment] 2016-04-27 16:39
@mkolar can you check if this is still a problem for you with the latest updates?

Currently it should be transferring much less data which should, aside from improving speed, also avoid the issue you were having here.

**Comment by mottosso** [comment] 2016-04-27 16:41
Yes, I should think so too!

**Comment by mkolar** [comment] 2016-05-02 16:31
I'll be getting back into some dev this week, so I'll let you guys know.

**Comment by larsbijl** [comment] 2016-05-02 16:44
just checked, It's works now.

**Closed as completed by larsbijl** 2016-05-02 16:44 UTC
Labels: bug
