### ISSUE TITLE
Collector plugins don't run with instance as argument.

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-base#243] opened 2016-02-01 10:01 UTC
**Repro**

``` python
import pyblish.api
import pyblish.util


class CollectContextInstance(pyblish.api.Collector):

    def process(self, instance, context):

        print 'CollectContextInstance'
        print context


pyblish.api.register_plugin(CollectContextInstance)
pyblish.util.publish()
```

Expected output is:

```
CollectContextInstance
[]
```

If you remove the instance as argument, you get the expected output;

``` python
import pyblish.api
import pyblish.util


class CollectContextInstance(pyblish.api.Collector):

    def process(self, context):

        print 'CollectContextInstance'
        print context


pyblish.api.register_plugin(CollectContextInstance)
pyblish.util.publish()
```

**Comment by mottosso** [comment] 2016-02-01 10:03
Thanks, having a look at this asap; quickest thing to do is to downgrade to 1.2.2 where this is confirmed to work properly.

Discussion thread: http://forums.pyblish.com/t/plugins-display-when-no-compatible-families-are-present

**Comment by mottosso** [comment] 2016-02-01 20:41
Ok, so I've had a closer look and it looks like this behaviour is intended.
- http://forums.pyblish.com/t/api-changes/51/19

With #242 in place, this (confusing) behaviour will vanish, but until then I would suggest maintaining the behaviour for backwards compatibility.

You mentioned you haven't seen this behaviour before? Can you confirm this? It's possible there was a discrepancy between the behaviour of pyblish-qml and `pyblish.util.publish()` in which case we'll need to pick one and consider it a breaking change for the other..

One of the recent changes in the pyblish-qml is likely at the root of this appearing, [#101](https://github.com/pyblish/pyblish-qml/issues/101).

What do we do?

**Comment by mottosso** [comment] 2016-02-01 20:43
To clarify why this behaviour is sound, when you request an `instance`, the plug-in essentially becomes a per-instance plug-in. But no instances were found, so the plug-in does nothing.

The act of requesting `instance` changes the behaviour of the plug-in.

This is in fact the primary reason for #242.

**Comment by tokejepsen** [comment] 2016-02-01 23:32
> What do we do?

This stems from @mkolar, so he is probably better to have in on this conversation.

**Comment by mottosso** [comment] 2016-02-02 06:35
Mm, well, it's not _just_ about us who are actively here to comment on things, but also about those that aren't. Whatever the solution, it'll need to work for a majority of users.

**Comment by mkolar** [comment] 2016-02-02 15:30
The problem I see here, is that if a collector tries to run on an instance that has been created with another collector that ran before it, It should be able to pick it up. 

I can definitely say that in pyblish-win 1.2.5 this was functional. Collector A creates an instance, Collector B running after it, picks it up and adds data to it. After update to 1.2.6 this behaviour got broken.

The question here that might need answering as I'm not sure about it's answer is. Does instance get created as soon as as it's collector is finished, thus making it available to any other plugins running after it. Or are instances created after all collectors are run.

**Comment by mottosso** [comment] 2016-02-02 19:56
> The problem I see here, is that if a collector tries to run on an instance that has been created with another collector that ran before it, It should be able to pick it up.

It sounds like you are describing a separate issue. Could you try and produce a reproducible of that, and make a separate issue?

If you run Toke's example above, I don't think it's meant to capture what you are referring to.

**Comment by mottosso** [comment] 2016-02-02 19:59
I think this is related to your issue, @mkolar. The context is being cached and not refreshed inbetween plug-ins.
- [https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/control.py#L694](https://github.com/pyblish/pyblish-qml/blob/389e2e4dae98ddaf0298e99c6dd6a6646698d4c4/pyblish_qml/control.py#L694)

Have a look at replacing the cached attribute with `context()`. And still make a separate issue please.

**Comment by mottosso** [comment] 2016-02-06 16:22
Closing this, as it looks like this behaviour has always been there, and I think it makes sense.

Asking for `instance`, when there aren't any instances, will cause your plug-in not to have anything to process.

@mkolar we should still have a look at your issue. I've made one [here](https://github.com/pyblish/pyblish-qml/issues/157).

**Comment by BigRoy** [comment] 2016-02-17 15:15
Ok. So this behavior still feels wrong. At least if it's related to [this](http://forums.pyblish.com/t/instanceplugin-not-running-as-collector/201).

Especially keeping in mind the described logic [here](http://forums.pyblish.com/t/api-changes/51/19?u=bigroy).

Based on that:
- Asking for instance will limit your plug-in to only process supported instances.
- Asking for instance when no instances are present, or only instances of unsupported families, the plug-in will never get run. Not even once.
- All plug-ins process at least once, unless limited to a particular set of families.

Now with InstancePlugin this would mean it would always run:
- if an instance is present and it doesn't require a specific family 
- or will run if an instance is present of a family that it requires. 

Currently it doesn't process all under any circumstances when the order is before the Validators, as described [here](http://forums.pyblish.com/t/instanceplugin-not-running-as-collector/201)

**Comment by mottosso** [comment] 2016-02-17 20:40
You're right, this was indeed a bug. Pushing a fix now!

**Closed as completed** 2016-02-20 09:49 UTC
Labels: bug, 1.3.1
